require 'bower-rails'
require "slim-rails"
require "less-rails"
require 'russian'
require 'angular-rails-templates'
require 'liquor'#, github: 'webgradus/liquor'
require 'carrierwave'
require 'active_model_serializers'
require 'ancestry'
require 'devise'
require 'devise/orm/active_record'
require 'evil-front'
require 'cancancan'
require 'dragonfly'
require 'textacular'
