require 'bower-rails'
require "slim-rails"
require "less-rails"
require 'russian'
require 'angular-rails-templates'
require 'liquor'#, github: 'webgradus/liquor'
require 'fog/aws'
require 'carrierwave'
require 'carrierwave/orm/activerecord'
require 'carrierwave/storage/fog'
require 'active_model_serializers'
require 'ancestry'
require 'devise'
require 'devise/orm/active_record'
#require 'evil-front'
require 'cancancan'
require 'dragonfly'
require 'textacular'
